### ISSUE TITLE
Upload to pypi

### ISSUE THREAD

**Issue by estebanfeldman** [bennylope/mongoengine-extras#2]
Would be nice to have this deployed to pypi :)

**Comment by bennylope** [comment]
I have to admit I haven't looked at this code in a while.

Have you been using it? If you can give me some feedback about how you've been using it and about anything that could be changed, improved, I'll gladly upload it to PyPI.

**Comment by estebanfeldman** [comment]
Hi, I'm trying to make AutoSlug populate_from to work, but I'm stuck, BTW found a typo:

https://github.com/bennylope/mongoengine-extras/blob/master/mongoengine_extras/fields.py#L23

If you have an idea on how to handle populate_from let me know, I can try to do it

**Comment by estebanfeldman** [comment]
I think I'm heading in a good direction on the populate_from... will send you a pull request. Ok? Thanks

**Comment by bennylope** [comment]
Thanks for the updates. 

http://pypi.python.org/pypi/mongoengine-extras/0.0.1

**Comment by estebanfeldman** [comment]
I think you should bump the version to 0.0.2, and thanks for putting it on pypi :)

**Comment by bennylope** [comment]
Well, given that it's up on PyPI as 0.0.1 I'm going to leave it for now. Any feature updates and we'll bump the version.
